# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-7.9

packages:
- '.'

extra-deps:
- store-0.3
- store-core-0.3

flags: {}
